### PR TITLE
FIXED SOM THINGZ 🔧

### PR DESCRIPTION
**Pull request by RXNationGMG**
YE BOI

### CODE REVIEW

**Comment by RXNationGMG** [comment]
Yo can this be merged?? @sitesgithub

**Comment by sitesgithub** [comment]
jesus christ this is dead, anyways. merging

**Comment by RXNationGMG** [comment]
> jesus christ this is dead, anyways. merging

K tnks :>

**Comment by RXNationGMG** [comment]
I should put a webhook support soon :)

**Pull request merged**
